module.exports = {
    IMG_WIDTH: 50,
    IMG_HEIGHT: 50,

    REFRESH_RATE: 60,
    DIFFICULTY: 4,

    UP_KEY: 32,

    TAKEOFF_PACE: 5,
    DIVING_PACE: 8,

    STARTING_X: 150,
    STARTING_Y: 200,

    CANVAS_WIDTH: 1000,
    CANVAS_HEIGHT: 600,

    GROUND_TOP_HEIGHT: 20,
    GROUND_BOTTOM_HEIGHT: 150,

    PIPE_TOP_WIDTH: 90,
    PIPE_TOP_HEIGHT: 35,
    PIPE_SPACE: 200,
    PIPE_BODY_WIDTH: 60,

    ONE_SECOND_MS: 1000
}